version: "3"

services:
   apache:
    image: httpd:alpine
    links:
      - phpfpm
      - elasticsearch1
    volumes:
      - ./public_html:/usr/local/apache2/htdocs/
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    environment:
      - FASTCGI=fcgi://phpfpm:9000
    hostname: "${HOSTNAME}"
    networks:
      static-network:
        ipv4_address: "${IPADDRESS}.5"

   phpfpm:
    build:
      context: .
      dockerfile: "./conf/php${PHP}"
    volumes:
      - ./public_html:/usr/local/apache2/htdocs/
      - ./conf/php.ini:/usr/local/etc/php/conf.d/50-setting.ini
    networks:
      static-network:
        ipv4_address: "${IPADDRESS}.6"

   elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./conf/elasticsearch1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      static-network:
        ipv4_address: "${IPADDRESS}.7"

   elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=${IPADDRESS}.7"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./conf/elasticsearch2:/usr/share/elasticsearch/data
    networks:
      static-network:
        ipv4_address: "${IPADDRESS}.8"

networks:
  static-network:
    ipam:
      config:
        - subnet: "${IPADDRESS}.0/28"